apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
components:
- ../../components/postgres-statefulset
- ../../components/traefik-hsts
patches:
- path: configmap-patch.yaml
- path: service-patch.yaml
secretGenerator:
- name: postgres-credentials
  envs:
  - secrets/postgres.env
  options:
    disableNameSuffixHash: true
- name: bugsink-secrets
  envs:
  - secrets/bugsink.env
  options:
    disableNameSuffixHash: true
